### ISSUE TITLE
Enhancements Items to work for official release

### ISSUE THREAD

**Issue by a-bouth** [ansys/pyansys-sound#34]
Enhancements for PyAnsys Sound first release:

### Tasks
- [ ] Consider utilizing the changelog action to automatically build release docs, and integrate it inside the documentation. See https://actions.docs.ansys.com/version/stable/migrations/docs-changelog-setup.html and https://actions.docs.ansys.com/version/stable/migrations/docs-deploy-changelog-setup.html
- [ ] Consider using ``autoapi`` for API docs - it will reduce maintenance burden. Reach out to @clatapie if needed.
- [x] Rename ``pyansys_sound.py`` to a private module name (e.g. ``_base.py``) si that users are not able to access it.
